# Generated by Django 4.1.5 on 2023-07-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja_Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('hora_apertura', models.TimeField(auto_now_add=True)),
                ('monto_inicial', models.FloatField()),
                ('fecha_cierre', models.DateField(auto_now=True, null=True)),
                ('hora_cierre', models.TimeField(auto_now=True, null=True)),
                ('monto_final', models.FloatField(null=True)),
                ('estado_caja', models.BooleanField(blank=True, default=False)),
                ('responsable_apertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_apertura', to='api_models.trabajador')),
                ('responsable_cierre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_cierre', to='api_models.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos_Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Venta pequeña', 'Venta pequeña'), ('Otros ingresos', 'Otros ingresos'), ('Otros egresos', 'Otros egresos')], max_length=250)),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='documents/caja_diaria/ingresos_otros')),
                ('tipo_pago', models.CharField(choices=[('Dolares', 'Dolares'), ('Soles', 'Soles')], max_length=50)),
                ('monto', models.FloatField()),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_otros', to='api_cajadiaria.caja_diaria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Venta pequeña', 'Venta pequeña'), ('Otros ingresos', 'Otros ingresos'), ('Otros egresos', 'Otros egresos')], max_length=250)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_venta', to='api_cajadiaria.caja_diaria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.venta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso_Sesion_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Venta pequeña', 'Venta pequeña'), ('Otros ingresos', 'Otros ingresos'), ('Otros egresos', 'Otros egresos')], max_length=250)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_sesion_venta', to='api_cajadiaria.caja_diaria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
                ('sesion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.sesion_venta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Egresos_Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Venta pequeña', 'Venta pequeña'), ('Otros ingresos', 'Otros ingresos'), ('Otros egresos', 'Otros egresos')], max_length=250)),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='documents/caja_diaria/egresos_otros')),
                ('tipo_pago', models.CharField(choices=[('Dolares', 'Dolares'), ('Soles', 'Soles')], max_length=50)),
                ('monto', models.FloatField()),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_otros', to='api_cajadiaria.caja_diaria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Egresos_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Venta pequeña', 'Venta pequeña'), ('Otros ingresos', 'Otros ingresos'), ('Otros egresos', 'Otros egresos')], max_length=250)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_compra', to='api_cajadiaria.caja_diaria')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.compra')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
