# Generated by Django 4.1.5 on 2023-06-14 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja_Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('hora_apertura', models.TimeField(auto_now_add=True)),
                ('monto_inicial', models.FloatField()),
                ('fecha_cierre', models.DateField(null=True)),
                ('hora_cierre', models.TimeField(null=True)),
                ('monto_final', models.FloatField(null=True)),
                ('estado_caja', models.BooleanField(blank=True, default=False)),
                ('responsable_apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_apertura', to=settings.AUTH_USER_MODEL)),
                ('responsable_cierre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_cierre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Otros ingresos', 'Otros ingresos'), ('Otros egresos', 'Otros egresos')], max_length=250)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cajadiaria.caja_diaria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Egresos_Otros',
            fields=[
                ('registros_caja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_cajadiaria.registros_caja')),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='documents/caja_diaria/egresos_otros')),
                ('tipo_pago', models.CharField(choices=[('Dolares', 'Dolares'), ('Soles', 'Soles')], max_length=50)),
            ],
            bases=('api_cajadiaria.registros_caja',),
        ),
        migrations.CreateModel(
            name='Ingresos_Otros',
            fields=[
                ('registros_caja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_cajadiaria.registros_caja')),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='documents/caja_diaria/ingresos_otros')),
                ('tipo_pago', models.CharField(choices=[('Dolares', 'Dolares'), ('Soles', 'Soles')], max_length=50)),
            ],
            bases=('api_cajadiaria.registros_caja',),
        ),
        migrations.CreateModel(
            name='Ingreso_Venta',
            fields=[
                ('registros_caja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_cajadiaria.registros_caja')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.venta')),
            ],
            bases=('api_cajadiaria.registros_caja',),
        ),
        migrations.CreateModel(
            name='Egresos_Compra',
            fields=[
                ('registros_caja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_cajadiaria.registros_caja')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.compra')),
            ],
            bases=('api_cajadiaria.registros_caja',),
        ),
    ]
