# Generated by Django 4.1.5 on 2023-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cajadiaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja_diaria',
            name='fecha_cierre',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='hora_cierre',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
