# Generated by Django 4.1.5 on 2023-06-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cajadiaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja_diaria',
            name='ultimo_monto_final',
            field=models.FloatField(default=0),
        ),
    ]
