# Generated by Django 4.1.5 on 2023-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cajadiaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos_otros',
            name='codigo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='egresos_otros',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingresos_otros',
            name='codigo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingresos_otros',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
