# Generated by Django 4.1.5 on 2023-06-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_remove_sesion_venta_monto_inicial'),
        ('api_cajadiaria', '0002_alter_caja_diaria_responsable_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros_caja',
            name='tipo',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Venta pequeña', 'Venta pequeña'), ('Otros ingresos', 'Otros ingresos'), ('Otros egresos', 'Otros egresos')], max_length=250),
        ),
        migrations.CreateModel(
            name='Ingreso_Sesion_Venta',
            fields=[
                ('registros_caja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_cajadiaria.registros_caja')),
                ('sesion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.sesion_venta')),
            ],
            bases=('api_cajadiaria.registros_caja',),
        ),
    ]
