# Generated by Django 4.1.5 on 2023-06-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cajadiaria', '0002_caja_diaria_ultimo_monto_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja_diaria',
            name='ultimo_monto_final',
        ),
    ]
