# Generated by Django 4.1.5 on 2023-06-22 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_cajadiaria', '0003_remove_caja_diaria_ultimo_monto_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja_diaria',
            name='responsable_apertura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_apertura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='responsable_cierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_cierre', to=settings.AUTH_USER_MODEL),
        ),
    ]
