# Generated by Django 4.1.5 on 2023-06-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cajadiaria', '0005_egresos_otros_monto_egreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresos_otros',
            old_name='monto_egreso',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='ingresos_otros',
            old_name='monto_ingreso',
            new_name='monto',
        ),
    ]
