# Generated by Django 4.1.5 on 2023-03-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_bien',
            name='bien_propuesta_economica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ordenes_bienes_servicios.propuesta_economica'),
        ),
        migrations.AlterField(
            model_name='orden_bien',
            name='bien_propuesta_tecnica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ordenes_bienes_servicios.propuesta_tecnica'),
        ),
    ]
