# Generated by Django 4.1.5 on 2023-04-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_bien',
            name='orden_bien',
        ),
        migrations.AddField(
            model_name='orden_bien',
            name='orden_bien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ordenes_bienes_servicios.propuesta_empresa_bien'),
        ),
    ]
