# Generated by Django 4.1.5 on 2023-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_bien',
            name='mayor_500',
            field=models.BooleanField(null=True),
        ),
    ]
