# Generated by Django 4.1.5 on 2023-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta_economica',
            name='propuesta_bien_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='propuesta_tecnica',
            name='propuesta_tecnica_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='propuesta_economica',
            name='propuesta_economica_nombre',
            field=models.CharField(default='Ninguno', max_length=100),
        ),
        migrations.AlterField(
            model_name='propuesta_tecnica',
            name='propuesta_tecnica_nombre',
            field=models.CharField(default='Ninguno', max_length=100),
        ),
    ]
