# Generated by Django 4.1.5 on 2023-04-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0002_propuesta_economica_propuesta_bien_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_bien',
            name='bien_cotizacion',
        ),
        migrations.AddField(
            model_name='orden_bien',
            name='bien_cotizacion_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/cotizacion'),
        ),
        migrations.AlterField(
            model_name='propuesta_economica',
            name='propuesta_bien_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/propuesta_economica'),
        ),
        migrations.AlterField(
            model_name='propuesta_tecnica',
            name='propuesta_tecnica_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/propuesta_tecnica'),
        ),
    ]
