# Generated by Django 4.1.5 on 2023-04-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0002_remove_orden_bien_orden_bien_orden_bien_orden_bien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_bien',
            name='orden_bien',
        ),
    ]
