# Generated by Django 4.1.5 on 2023-03-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0002_alter_orden_bien_bien_propuesta_economica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_bien',
            name='bien_propuesta_economica',
        ),
        migrations.RemoveField(
            model_name='orden_bien',
            name='bien_propuesta_tecnica',
        ),
        migrations.AddField(
            model_name='propuesta_economica',
            name='orden_bien_economico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ordenes_bienes_servicios.orden_bien'),
        ),
        migrations.AddField(
            model_name='propuesta_tecnica',
            name='orden_bien_tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ordenes_bienes_servicios.orden_bien'),
        ),
        migrations.AlterField(
            model_name='propuesta_economica',
            name='propuesta_economica_tipo',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Servicio', 'Servicio'), ('Bien', 'Bien')], default='Ninguno', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propuesta_tecnica',
            name='propuesta_tecnica_tipo',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Servicio', 'Servicio'), ('Bien', 'Bien')], default='Ninguno', max_length=50, null=True),
        ),
    ]
