# Generated by Django 4.1.5 on 2023-07-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0003_propuesta_empresa_servicio_documentos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_bien',
            name='uso_en_compra',
            field=models.BooleanField(default=False),
        ),
    ]
