# Generated by Django 4.1.5 on 2023-04-23 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
        ('api_ordenes_bienes_servicios', '0003_remove_orden_bien_bien_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateField(auto_now=True)),
                ('orden_bien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_bien_tecnico', to='api_ordenes_bienes_servicios.orden_bien')),
                ('propuesta_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta_Empresa_Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propuesta_tecnica_documento', models.FileField(blank=True, null=True, upload_to='documents/propuesta_tecnica')),
                ('propuesta_economica_documento', models.FileField(blank=True, null=True, upload_to='documents/propuesta_economica')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateField(auto_now=True)),
                ('propuesta_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ordenes_bienes_servicios.propuesta_empresa')),
            ],
        ),
        migrations.RemoveField(
            model_name='propuesta_tecnica',
            name='orden_bien_tecnico',
        ),
        migrations.DeleteModel(
            name='Propuesta_economica',
        ),
        migrations.DeleteModel(
            name='Propuesta_tecnica',
        ),
    ]
