# Generated by Django 4.1.5 on 2023-04-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0004_propuesta_empresa_bien_orden_bien_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta_empresa_bien',
            name='orden_bien_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_bien', to='api_ordenes_bienes_servicios.orden_bien'),
        ),
    ]
