# Generated by Django 4.1.5 on 2023-07-23 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_requerimientos', '0004_alter_requerimiento_almacen'),
        ('api_ordenes_bienes_servicios', '0004_orden_bien_uso_en_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta_empresa_bien_documentos',
            name='requerimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_requerimientos.requerimiento'),
        ),
        migrations.AddField(
            model_name='propuesta_empresa_servicio_documentos',
            name='requerimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_requerimientos.requerimiento'),
        ),
    ]
