# Generated by Django 4.1.5 on 2023-04-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0005_alter_propuesta_empresa_bien_orden_bien_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuesta_empresa_bien',
            old_name='orden_bien_id',
            new_name='orden_bien',
        ),
    ]
