# Generated by Django 4.1.5 on 2023-07-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_requerimientos', '0004_alter_requerimiento_almacen'),
        ('api_ordenes_bienes_servicios', '0005_propuesta_empresa_bien_documentos_requerimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta_empresa_bien_documentos',
            name='requerimiento',
        ),
        migrations.RemoveField(
            model_name='propuesta_empresa_servicio_documentos',
            name='requerimiento',
        ),
        migrations.AddField(
            model_name='orden_bien',
            name='requerimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_requerimientos.requerimiento'),
        ),
        migrations.AddField(
            model_name='orden_servicio',
            name='requerimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_requerimientos.requerimiento'),
        ),
    ]
