# Generated by Django 4.1.5 on 2023-04-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0005_propuesta_empresa_bien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuesta_empresa_bien',
            old_name='orden_bien',
            new_name='propuesta_bien',
        ),
        migrations.RenameField(
            model_name='propuesta_empresa_bien',
            old_name='propuesta_proveedor',
            new_name='proveedor_id',
        ),
        migrations.RenameField(
            model_name='propuesta_empresa_bien_documentos',
            old_name='bien_cotizacion_archivo',
            new_name='bien_cotizacion_documento',
        ),
        migrations.AlterField(
            model_name='propuesta_empresa_bien_documentos',
            name='propuesta_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propuesta_documentos_bien', to='api_ordenes_bienes_servicios.propuesta_empresa_bien'),
        ),
    ]
