# Generated by Django 4.1.5 on 2023-04-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0006_rename_orden_bien_propuesta_empresa_bien_propuesta_bien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuesta_empresa_bien_documentos',
            old_name='propuesta_empresa',
            new_name='propuesta_empresa_id',
        ),
    ]
