# Generated by Django 4.1.5 on 2023-04-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0007_rename_propuesta_empresa_propuesta_empresa_bien_documentos_propuesta_empresa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuesta_empresa_bien_documentos',
            old_name='propuesta_empresa_id',
            new_name='propuesta_empresa',
        ),
    ]
