# Generated by Django 4.1.5 on 2023-04-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0008_rename_propuesta_empresa_id_propuesta_empresa_bien_documentos_propuesta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta_empresa_bien_documentos',
            name='encargado',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
