# Generated by Django 4.1.5 on 2023-04-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0009_propuesta_empresa_bien_documentos_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta_empresa_bien_documentos',
            name='encargado',
        ),
    ]
