# Generated by Django 4.1.5 on 2023-04-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0010_remove_propuesta_empresa_bien_documentos_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta_empresa_bien',
            name='propuesta_bien',
        ),
        migrations.RemoveField(
            model_name='propuesta_empresa_bien_documentos',
            name='propuesta_empresa',
        ),
        migrations.AddField(
            model_name='orden_bien',
            name='orden_bien',
            field=models.ManyToManyField(null=True, to='api_ordenes_bienes_servicios.propuesta_empresa_bien'),
        ),
        migrations.AddField(
            model_name='propuesta_empresa_bien',
            name='propuesta_documentos_bien',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_ordenes_bienes_servicios.propuesta_empresa_bien_documentos'),
            preserve_default=False,
        ),
    ]
