# Generated by Django 4.1.5 on 2023-02-07 18:01

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=5000)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('aviso_minimo', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3)),
                ('fecha_alta', models.DateField()),
                ('unidades_por_caja', models.PositiveIntegerField(default=0)),
                ('observaciones', models.CharField(max_length=500)),
                ('precio_compra', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precio_venta', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precio_bruto', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen')),
                ('tipo', models.CharField(choices=[('Materia Prima', 'Materia Prima'), ('Insumo', 'Insumo'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=50)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja_diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, null=True)),
                ('monto_total_inicial', models.FloatField(default=0, null=True)),
                ('monto_total_final', models.FloatField(default=0, null=True)),
                ('total_ventas', models.FloatField(default=0, null=True)),
                ('total_compras', models.FloatField(default=0, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_prov_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField(null=True)),
                ('dsctoproducto', models.FloatField(blank=True, default=0, null=True)),
                ('remision_hecha', models.BooleanField(blank=True, default=False, null=True)),
                ('codproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Embalajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=100)),
                ('ruc', models.CharField(default='-', max_length=100)),
                ('estructurajuridica', models.CharField(default='-', max_length=100)),
                ('tipo', models.CharField(default='-', max_length=100)),
                ('localidad', models.CharField(default='-', max_length=100)),
                ('direccion', models.CharField(default='-', max_length=500)),
                ('codpostal', models.CharField(default='-', max_length=100)),
                ('cuentabancaria', models.CharField(default='-', max_length=100)),
                ('telefono', models.CharField(default='-', max_length=100)),
                ('movil', models.CharField(default='-', max_length=100)),
                ('web', models.CharField(default='-', max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreentidad', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('iva', models.IntegerField()),
                ('totalfactura', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formapago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrefp', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_compra_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden_servicio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=100)),
                ('dni', models.CharField(default='-', max_length=100)),
                ('localidad', models.CharField(default='-', max_length=100)),
                ('direccion', models.CharField(default='-', max_length=500)),
                ('codpostal', models.CharField(default='-', max_length=100)),
                ('cuentabancaria', models.CharField(default='-', max_length=100)),
                ('telefono', models.CharField(default='-', max_length=100)),
                ('movil', models.CharField(default='-', max_length=100)),
                ('web', models.CharField(default='-', max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField()),
                ('estdo_produccion', models.CharField(choices=[('No Iniciado', 'No Iniciado'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Saliendo', 'Saliendo')], default='No Iniciado', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('precio_final', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('color', models.TextField(blank=True, null=True)),
                ('talla', models.TextField(blank=True, null=True)),
                ('precio_horas_manufactura', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('horas_manufactura', models.IntegerField(default=0)),
                ('costos_extra', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precio_inicial', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprovincia', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remision_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Remision_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_remision', models.DateField(auto_now_add=True)),
                ('contador', models.IntegerField(default=0, null=True)),
                ('estado', models.CharField(choices=[('No Enviado', 'No Enviado'), ('Enviado', 'Enviado')], default='No Enviado', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_prov',
            fields=[
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_models.factura')),
                ('imagen_fac_compra', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen_fac_compra')),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('detaller_entrega', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta_clie',
            fields=[
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_models.factura')),
                ('estadoprod', models.BooleanField(default=False, null=True)),
                ('contador_productos', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta_clie_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField(null=True)),
                ('dsctoproducto', models.FloatField()),
                ('remision_hecha', models.BooleanField(blank=True, default=False, null=True)),
                ('codproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.producto')),
                ('venta_clie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_clie')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajador', models.CharField(choices=[('Interno', 'Interno'), ('Contratista', 'Contratista'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=30)),
                ('borrado', models.CharField(default=0, max_length=1)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.empresa')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_compra', models.FloatField(null=True)),
                ('orden_compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.orden_compra_servicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Remision_venta_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_clie_detalle')),
                ('codremision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.remision_venta')),
            ],
        ),
        migrations.CreateModel(
            name='Remision_linea_prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.compra_prov_detalle')),
                ('codremision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.remision_compra')),
            ],
        ),
        migrations.CreateModel(
            name='Recibir_orden_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField()),
                ('costo_total', models.FloatField()),
                ('orden_compra_referencia', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.orden_compra_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.empresa')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('borrado', models.BooleanField(default=False, null=True)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.articulos')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_detalle', to='api_models.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estdo_produccion_prod', models.CharField(choices=[('No Iniciado', 'No Iniciado'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Saliendo', 'Saliendo')], default='No Iniciado', max_length=100)),
                ('cod_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_clie_detalle')),
                ('produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.produccion')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='codprovincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.provincias'),
        ),
        migrations.AddField(
            model_name='orden_compra_servicio',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador'),
        ),
        migrations.CreateModel(
            name='Libro_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=20)),
                ('obtener_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.factura')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='codprovincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.provincias'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrado', models.BooleanField(default=False, null=True)),
                ('codformapago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.formapago')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.empresa')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.persona')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.categoria'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='embalaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.embalajes'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.impuestos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.proveedores'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen'),
        ),
        migrations.AddField(
            model_name='venta_clie',
            name='codcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.clientes'),
        ),
        migrations.AddField(
            model_name='remision_venta',
            name='factura_venta_clie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_clie'),
        ),
        migrations.AddField(
            model_name='remision_compra',
            name='factura_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.compra_prov'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='factura_clie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_clie'),
        ),
        migrations.AddField(
            model_name='compra_prov_detalle',
            name='compra_prov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.compra_prov'),
        ),
        migrations.AddField(
            model_name='compra_prov',
            name='codprov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.proveedores'),
        ),
        migrations.CreateModel(
            name='Caja_tipo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tipo_pago', models.FloatField(null=True)),
                ('caja_diaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.caja_diaria')),
                ('tipo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.formapago')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.compra_prov')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_clie')),
            ],
        ),
    ]
