# Generated by Django 4.1.5 on 2023-04-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja_diaria_movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='libro_diario',
            name='obtener_factura',
        ),
        migrations.RenameField(
            model_name='caja_diaria',
            old_name='monto_total_final',
            new_name='monto_final',
        ),
        migrations.RenameField(
            model_name='caja_diaria',
            old_name='monto_total_inicial',
            new_name='monto_inicial',
        ),
        migrations.RemoveField(
            model_name='caja_diaria',
            name='total_compras',
        ),
        migrations.RemoveField(
            model_name='caja_diaria',
            name='total_ventas',
        ),
        migrations.AddField(
            model_name='caja_diaria',
            name='descripcion',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='caja_diaria',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.trabajador'),
        ),
        migrations.DeleteModel(
            name='Caja_tipo_pago',
        ),
        migrations.DeleteModel(
            name='Libro_diario',
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='caja_diaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.caja_diaria'),
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.compra'),
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='tipo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.formapago'),
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta'),
        ),
    ]
