# Generated by Django 4.1.5 on 2023-03-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='observaciones',
            new_name='detalle_entrega',
        ),
    ]
