# Generated by Django 4.1.5 on 2023-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='numero_factura',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='detalle_entrega',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
