# Generated by Django 4.1.5 on 2023-02-15 15:36

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='NO_CLASIFICADO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(default='-', max_length=100)),
                ('marca', models.CharField(default='-', max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_compra', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.categoria')),
                ('embalaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.embalajes')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('cantidad_solicitada', models.PositiveIntegerField(default=0)),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('completo', 'completo'), ('incompleto', 'incompleto')], default='incompleto', max_length=100)),
                ('area_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_entrega', to='api_models.areas')),
                ('area_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_solicitante', to='api_models.areas')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.articulo')),
                ('trabajador_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_entrega', to='api_models.trabajador')),
                ('trabajador_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_solicitante', to='api_models.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AddField(
            model_name='almacen',
            name='ubicacion',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.CreateModel(
            name='SalidaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_clie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalidaRequerimientoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.requerimientosalida')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requerimientosalida',
            name='unidad_recibida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_recibida', to='api_models.unidad'),
        ),
        migrations.AddField(
            model_name='requerimientosalida',
            name='unidad_solicitada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_solicitante', to='api_models.unidad'),
        ),
        migrations.CreateModel(
            name='EntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.compra_prov')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.trabajador')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticulosEnAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ubicacion', models.CharField(default='-', max_length=300)),
                ('observaciones', models.CharField(default='-', max_length=500)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.articulo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad'),
        ),
        migrations.CreateModel(
            name='AlmacenProductosTerminados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(default='-', max_length=300)),
                ('observaciones', models.CharField(default='-', max_length=500)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
                ('productos_terminados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.areas'),
        ),
    ]
