# Generated by Django 4.1.5 on 2023-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
