# Generated by Django 4.1.5 on 2023-06-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaventa',
            name='unidad',
        ),
    ]
