# Generated by Django 4.1.5 on 2023-03-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_user',
            name='area',
        ),
        migrations.RemoveField(
            model_name='profile_user',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='profile_user',
            name='fecha_ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='profile_user',
            name='rol',
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
