# Generated by Django 4.1.5 on 2023-07-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordenes_bienes_servicios', '0004_orden_bien_uso_en_compra'),
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='orden_bien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_ordenes_bienes_servicios.orden_bien'),
        ),
    ]
