# Generated by Django 4.1.5 on 2023-03-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.FloatField(default=0, null=True)),
                ('responsable', models.CharField(max_length=100)),
                ('hora_fin', models.DateTimeField()),
                ('monto_final', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punto_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('precio_total', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.clientes')),
                ('sesion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punto_venta', to='api_models.sesion_venta')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.FloatField(default=0)),
                ('Producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.producto')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta', to='api_models.punto_venta')),
            ],
        ),
    ]
