# Generated by Django 4.1.5 on 2023-02-21 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='horas_manufactura',
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_manufactura',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
