# Generated by Django 4.1.5 on 2023-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
