# Generated by Django 4.1.5 on 2023-02-01 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='compra_prov',
            name='imagen_fac_compra',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen_fac_compra'),
        ),
    ]
