# Generated by Django 4.1.5 on 2023-04-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='estdo_produccion',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='produccion_detalle',
            name='estdo_produccion_prod',
            field=models.CharField(choices=[('Cancelado', 'Cancelado'), ('No Iniciado', 'No Iniciado'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Saliendo', 'Saliendo')], default='No Iniciado', max_length=100),
        ),
    ]
