# Generated by Django 4.1.5 on 2023-06-29 03:59

import api_models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='area',
            field=models.ForeignKey(default=api_models.models.get_default_area, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.areas'),
        ),
    ]
