# Generated by Django 4.1.5 on 2023-03-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulovariante',
            old_name='nombre',
            new_name='nombre_variante',
        ),
    ]
