# Generated by Django 4.1.5 on 2023-06-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_rename_estdo_produccion_produccion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(default='Tiempo completo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_contrato',
            field=models.CharField(choices=[('Tiempo parcial', 'Tiempo parcial'), ('Tiempo completo', 'Tiempo completo')], default='Tiempo completo', max_length=30),
        ),
    ]
