# Generated by Django 4.1.5 on 2023-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_caja_diaria_movimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
    ]
