# Generated by Django 4.1.5 on 2023-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_compra_numero_factura_alter_compra_detalle_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
