# Generated by Django 4.1.5 on 2023-03-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_rename_nombre_articulovariante_nombre_variante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulovariante',
            old_name='nombre_variante',
            new_name='nombre',
        ),
    ]
