# Generated by Django 4.1.5 on 2023-02-21 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_remove_producto_horas_manufactura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_inicial',
        ),
        migrations.AddField(
            model_name='producto',
            name='gastos_generales',
            field=models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
