# Generated by Django 4.1.5 on 2023-06-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_alter_profile_user_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_user',
            name='area',
        ),
    ]
