# Generated by Django 4.1.5 on 2023-02-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_alter_articulos_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
