# Generated by Django 4.1.5 on 2023-03-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_sesion_venta_punto_venta_detalle_venta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_venta',
            new_name='Detalle_punto_venta',
        ),
    ]
