# Generated by Django 4.1.5 on 2023-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_areas_articulo_requerimientosalida_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
