# Generated by Django 4.1.5 on 2023-03-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_alter_compra_fecha_alter_compradetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('totalCompra', models.FloatField(default=0, null=True)),
                ('descuento', models.FloatField(default=0, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.clientes')),
            ],
        ),
        migrations.RemoveField(
            model_name='venta_clie_detalle',
            name='codproducto',
        ),
        migrations.RemoveField(
            model_name='venta_clie_detalle',
            name='venta_clie',
        ),
        migrations.CreateModel(
            name='Venta_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, null=True)),
                ('precio_unitario', models.FloatField(default=0, null=True)),
                ('dscto_unitario', models.FloatField(blank=True, default=0, null=True)),
                ('precio_final', models.FloatField(default=0, null=True)),
                ('remision_hecha', models.BooleanField(blank=True, default=False, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.producto_variante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta', to='api_models.venta')),
            ],
        ),
        migrations.AlterField(
            model_name='caja_tipo_pago',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='factura_clie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta'),
        ),
        migrations.AlterField(
            model_name='produccion_detalle',
            name='cod_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_detalle'),
        ),
        migrations.AlterField(
            model_name='remision_venta',
            name='factura_venta_clie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.venta'),
        ),
        migrations.AlterField(
            model_name='remision_venta_detalle',
            name='codproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta_detalle'),
        ),
        migrations.AlterField(
            model_name='salidaventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.venta'),
        ),
        migrations.DeleteModel(
            name='Venta_clie',
        ),
        migrations.DeleteModel(
            name='Venta_clie_detalle',
        ),
    ]
