# Generated by Django 4.1.5 on 2023-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_venta_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
