# Generated by Django 4.1.5 on 2023-03-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_rename_observaciones_compra_detalle_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='totalCompra',
        ),
    ]
