# Generated by Django 4.1.5 on 2023-06-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_remove_salidaventa_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.producto_variante')),
            ],
        ),
        migrations.DeleteModel(
            name='SalidaVenta',
        ),
    ]
