# Generated by Django 4.1.5 on 2023-06-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_remove_profile_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
