# Generated by Django 4.1.5 on 2023-04-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_venta_numero_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_variante',
            old_name='gastos_generales',
            new_name='costo_produccion',
        ),
        migrations.RemoveField(
            model_name='producto_variante',
            name='costo_manufactura',
        ),
        migrations.RemoveField(
            model_name='producto_variante',
            name='horas_manufactura',
        ),
        migrations.RemoveField(
            model_name='punto_venta',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='sesion_venta',
            name='monto_final',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
