# Generated by Django 4.1.5 on 2023-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_rename_detalle_venta_detalle_punto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion_venta',
            name='hora_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
