# Generated by Django 4.1.5 on 2023-03-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_compra_borrado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='detalle_entrega',
            new_name='observaciones',
        ),
    ]
