# Generated by Django 4.1.5 on 2023-03-17 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_remove_compra_totalcompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remisiondetallecompra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='remisiondetallecompra',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='remisioncompra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remisioncompra',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.trabajador'),
        ),
    ]
