# Generated by Django 4.1.5 on 2023-03-08 15:04

import api_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_venta_remove_venta_clie_detalle_codproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='totalCompra',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='blancos.png', upload_to=api_models.models.upload_toProd, verbose_name='Image'),
        ),
    ]
