# Generated by Django 4.1.5 on 2023-02-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_remove_producto_precio_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='horas_manufactura',
            field=models.IntegerField(default=0),
        ),
    ]
