# Generated by Django 4.1.5 on 2023-02-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_alter_compradetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='compra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compra', to='api_models.compra'),
            preserve_default=False,
        ),
    ]
