# Generated by Django 4.1.5 on 2023-03-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_alter_sesion_venta_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_punto_venta',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_punto_venta', to='api_models.punto_venta'),
        ),
        migrations.AlterField(
            model_name='sesion_venta',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
