# Generated by Django 4.1.5 on 2023-02-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_alter_areas_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
