# Generated by Django 4.1.5 on 2023-03-09 14:54

import api_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_rename_totalcompra_venta_total_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='imagen_fac_compra',
            field=models.ImageField(blank=True, default='blancos.png', upload_to=api_models.models.upload_toCom, verbose_name='Image'),
        ),
    ]
