# Generated by Django 4.1.5 on 2023-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_producto_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_detalle',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
