# Generated by Django 4.1.5 on 2023-02-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_producto_horas_manufactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_detalle',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='api_models.articulovariante'),
        ),
    ]
