# Generated by Django 4.1.5 on 2023-04-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_rename_gastos_generales_producto_variante_costo_produccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_variante',
            name='precio_final',
        ),
    ]
