# Generated by Django 4.1.5 on 2023-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_rename_detalle_entrega_compra_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiondetallecompra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
