# Generated by Django 4.1.5 on 2023-03-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_alter_compra_imagen_fac_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remision_venta_detalle',
            old_name='codproducto',
            new_name='venta_detalle',
        ),
        migrations.RemoveField(
            model_name='remision_venta',
            name='contador',
        ),
        migrations.RemoveField(
            model_name='remision_venta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='remision_venta',
            name='factura_venta_clie',
        ),
        migrations.RemoveField(
            model_name='remision_venta',
            name='fecha_remision',
        ),
        migrations.RemoveField(
            model_name='remision_venta_detalle',
            name='codremision',
        ),
        migrations.AddField(
            model_name='producto_variante',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.almacen'),
        ),
        migrations.AddField(
            model_name='remision_venta',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remision_venta', to='api_models.venta'),
        ),
        migrations.AddField(
            model_name='remision_venta_detalle',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='remision_venta_detalle',
            name='remision_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remision_venta_detalle', to='api_models.remision_venta'),
        ),
        migrations.AddField(
            model_name='remision_venta_detalle',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.trabajador'),
        ),
    ]
