# Generated by Django 4.1.5 on 2023-02-22 13:28

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_alter_producto_detalle_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='costo_manufactura',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='gastos_generales',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='horas_manufactura',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_final',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='producto_detalle',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.CreateModel(
            name='Producto_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, default='-', null=True)),
                ('talla', models.TextField(blank=True, default='-', null=True)),
                ('horas_manufactura', models.IntegerField(default=0)),
                ('costo_manufactura', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gastos_generales', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precio_final', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('borrado', models.BooleanField(default=False, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_detalle', to='api_models.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto_detalle',
            name='vercion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_detalle', to='api_models.producto_version'),
        ),
    ]
