# Generated by Django 4.1.5 on 2023-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_remove_producto_variante_precio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto_venta',
            name='detalle_entrega',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='detalle_entrega',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
