# Generated by Django 4.1.5 on 2023-02-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_producto_detalle_borrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_detalle', to='api_models.producto'),
        ),
    ]
