# Generated by Django 4.1.5 on 2023-03-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_alter_detalle_punto_venta_punto_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_punto_venta',
            name='Producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.producto'),
        ),
        migrations.AlterField(
            model_name='punto_venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.clientes'),
        ),
    ]
