# Generated by Django 4.1.5 on 2023-02-15 19:57

import api_models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_areas_abreviacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='area',
            field=models.ForeignKey(default=api_models.models.get_default_area, on_delete=django.db.models.deletion.CASCADE, to='api_models.areas'),
        ),
    ]
