# Generated by Django 4.1.5 on 2023-06-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_alter_trabajador_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='codprovincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.provincias'),
        ),
    ]
