# Generated by Django 4.1.5 on 2023-03-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0006_alter_detalle_punto_venta_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_punto_venta',
            name='Producto',
        ),
        migrations.AddField(
            model_name='detalle_punto_venta',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.producto_variante'),
        ),
    ]
