# Generated by Django 4.1.5 on 2023-02-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0006_alter_producto_detalle_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_detalle',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.articulos'),
        ),
        migrations.AlterField(
            model_name='producto_detalle',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_detalle', to='api_models.producto'),
        ),
    ]
