# Generated by Django 4.1.5 on 2023-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0006_punto_venta_detalle_entrega_venta_detalle_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto_venta',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sesion_venta',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
