# Generated by Django 4.1.5 on 2023-02-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0006_alter_trabajador_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.proveedores'),
        ),
    ]
