# Generated by Django 4.1.5 on 2023-02-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0007_alter_articulo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='embalaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.embalajes'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad'),
        ),
    ]
