# Generated by Django 4.1.5 on 2023-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0007_producto_variante_remove_producto_detalle_vercion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_variante',
            name='color',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto_variante',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto_variante',
            name='talla',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
