# Generated by Django 4.1.5 on 2023-04-13 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0007_punto_venta_borrado_sesion_venta_borrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja_diaria_movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro_diario',
            name='obtener_factura',
        ),
        migrations.RenameField(
            model_name='caja_diaria',
            old_name='monto_total_final',
            new_name='monto_final',
        ),
        migrations.RenameField(
            model_name='caja_diaria',
            old_name='monto_total_inicial',
            new_name='monto_inicial',
        ),
        migrations.RemoveField(
            model_name='caja_diaria',
            name='total_compras',
        ),
        migrations.RemoveField(
            model_name='caja_diaria',
            name='total_ventas',
        ),
        migrations.RemoveField(
            model_name='remision_venta_detalle',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='remision_venta_detalle',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='caja_diaria',
            name='descripcion',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='caja_diaria',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.trabajador'),
        ),
        migrations.AddField(
            model_name='remision_venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remision_venta',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.trabajador'),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Caja_tipo_pago',
        ),
        migrations.DeleteModel(
            name='Libro_diario',
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='caja_diaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.caja_diaria'),
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.compra'),
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='tipo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.formapago'),
        ),
        migrations.AddField(
            model_name='caja_diaria_movimientos',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.venta'),
        ),
    ]
