# Generated by Django 4.1.5 on 2023-04-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0008_caja_diaria_movimientos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_variante',
            name='almacen',
        ),
        migrations.CreateModel(
            name='Ubicacion_almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, null=True)),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
            ],
        ),
        migrations.AddField(
            model_name='producto_variante',
            name='ubicacion_almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.ubicacion_almacen'),
        ),
    ]
