# Generated by Django 4.1.5 on 2023-02-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0008_alter_articulo_categoria_alter_articulo_embalaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
