# Generated by Django 4.1.5 on 2023-02-17 00:10

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0009_articulo_borrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('detalle_entrega', models.TextField(blank=True, null=True)),
                ('totalCompra', models.FloatField(default=0, null=True)),
                ('imagen_fac_compra', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen_fac_compra')),
                ('descuento', models.FloatField(default=0, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('dscto_unitario', models.FloatField(blank=True, default=0, null=True)),
                ('remision_hecha', models.BooleanField(blank=True, default=False, null=True)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.articulovariante')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='api_models.compra')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='RemisionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.compra')),
            ],
        ),
        migrations.RenameField(
            model_name='articulosenalmacen',
            old_name='articulo',
            new_name='articulo_variante',
        ),
        migrations.RemoveField(
            model_name='almacenproductosterminados',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='embalaje',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='articulosenalmacen',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='articulosenalmacen',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='entradacompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='entradacompra',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='empresa',
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='trabajador_emisor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_emisor', to='api_models.trabajador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='trabajador_receptor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_receptor', to='api_models.trabajador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.categoria'),
        ),
        migrations.CreateModel(
            name='RemisionDetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.compradetalle')),
                ('remision_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.remisioncompra')),
            ],
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.articulo'),
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='embalaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.embalajes'),
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.unidad'),
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.compradetalle'),
        ),
    ]
