# Generated by Django 4.1.5 on 2023-04-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0009_remove_producto_variante_almacen_ubicacion_almacen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
