# Generated by Django 4.1.5 on 2023-04-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0010_remove_producto_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_variante',
            old_name='ubicacion_almacen',
            new_name='almacen',
        ),
    ]
