# Generated by Django 4.1.5 on 2023-02-17 15:08

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0011_alter_compradetalle_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulovariante',
            name='imagen',
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1675259440/erp/Blancos_aoyyl7.png', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='nombre',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='observaciones',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='ubicacion',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compra', to='api_models.compra'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.unidad'),
        ),
        migrations.DeleteModel(
            name='ArticulosEnAlmacen',
        ),
    ]
