# Generated by Django 4.1.5 on 2023-04-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0011_rename_ubicacion_almacen_producto_variante_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion_almacen_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, null=True)),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto_variante',
            name='almacen',
        ),
        migrations.DeleteModel(
            name='Ubicacion_almacen',
        ),
        migrations.AddField(
            model_name='ubicacion_almacen_producto',
            name='producto_variante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_producto', to='api_models.producto_variante'),
        ),
    ]
