# Generated by Django 4.1.5 on 2023-02-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0012_remove_articulovariante_imagen_articulo_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulovariante',
            name='unidad',
        ),
    ]
