# Generated by Django 4.1.5 on 2023-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0012_ubicacion_almacen_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaventa',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
