# Generated by Django 4.1.5 on 2023-02-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0013_remove_articulovariante_unidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulovariante',
            old_name='observaciones',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='articulovariante',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.almacen'),
        ),
    ]
