# Generated by Django 4.1.5 on 2023-02-20 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0014_rename_observaciones_articulovariante_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisioncompra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remisioncompra',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.trabajador'),
        ),
        migrations.AlterField(
            model_name='entradacompra',
            name='descripcion',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='remisiondetallecompra',
            name='remision_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remision_compra', to='api_models.remisioncompra'),
        ),
    ]
