# Generated by Django 4.1.5 on 2023-02-20 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0015_remisioncompra_fecha_remisioncompra_trabajador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remisioncompra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='remisioncompra',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='remisiondetallecompra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remisiondetallecompra',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_models.trabajador'),
        ),
        migrations.AlterField(
            model_name='remisioncompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remision_compra', to='api_models.compra'),
        ),
        migrations.AlterField(
            model_name='remisiondetallecompra',
            name='remision_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remision_compra_detalle', to='api_models.remisioncompra'),
        ),
    ]
