# Generated by Django 4.1.5 on 2023-02-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0017_alter_remisiondetallecompra_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaAlmacenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(default='-', max_length=300)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.remisioncompra')),
                ('trabajador_receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador_receptor', to='api_models.trabajador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EntradaCompra',
        ),
    ]
