# Generated by Django 4.1.5 on 2023-02-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0018_entradaalmacencompra_delete_entradacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaalmacencompra',
            name='remision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.remisiondetallecompra'),
        ),
    ]
