# Generated by Django 4.1.5 on 2023-02-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0019_alter_entradaalmacencompra_remision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulovariante',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='api_models.articulo'),
        ),
    ]
