# Generated by Django 4.1.5 on 2023-07-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona_requerimiento', models.CharField(max_length=50, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('hora_registro', models.TimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateField(auto_now=True, null=True)),
                ('hora_modificacion', models.TimeField(auto_now=True, null=True)),
                ('area_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento_Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona_requerimiento', models.CharField(max_length=50, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('hora_registro', models.TimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateField(auto_now=True, null=True)),
                ('hora_modificacion', models.TimeField(auto_now=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen')),
                ('area_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.areas')),
            ],
        ),
    ]
