# Generated by Django 4.1.5 on 2023-07-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento_bien',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_bien',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_bien',
            name='hora_modificacion',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_bien',
            name='hora_registro',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_servicio',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_servicio',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_servicio',
            name='hora_modificacion',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_servicio',
            name='hora_registro',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
