# Generated by Django 4.1.5 on 2023-07-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_requerimientos', '0002_requerimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimiento',
            name='hora_modificacion',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='hora_registro',
        ),
    ]
