# Generated by Django 4.1.5 on 2023-07-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_requerimientos', '0002_requerimiento_bien_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento_bien',
            name='nombre_persona_requerimiento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento_servicio',
            name='nombre_persona_requerimiento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
