# Generated by Django 4.1.5 on 2023-07-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0001_initial'),
        ('api_requerimientos', '0003_remove_requerimiento_hora_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.almacen'),
        ),
    ]
